### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by cjsampson**

### CODE REVIEW

**Comment by yanula20** [comment]
Saw your e-mails. I'll call u later to chat about it. I am working on a lab
right now in the IT Security Professional program. Pre-cursor classes to
get my hacking up.
BTW, Westbrook is looking good.

**Comment by cjsampson** [comment]
Heard that. Tomas and I have been working on our portfolios and sites and they say delete the boilerplate readmes. Hit me up whenever.

Laters

**Comment by yanula20** [comment]
Tell Tomas I said 'whaddup?!!'.

**Comment by cjsampson** [comment]
Yes sir!  Just got out of the gym.  I will hit you up tomorrow for a bit.

**Pull request merged**
